// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGRtRDux0la6fsSv9eGWVNSPP2Efn3CV0',
    appId: '1:198070192196:web:9cddc885aa0684171c5411',
    messagingSenderId: '198070192196',
    projectId: 'green-thumb-6a158',
    authDomain: 'green-thumb-6a158.firebaseapp.com',
    storageBucket: 'green-thumb-6a158.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmpeDtRGEIH4sT_8R65R2x6z5Xq_-NY7I',
    appId: '1:198070192196:android:d258847f986c5c8c1c5411',
    messagingSenderId: '198070192196',
    projectId: 'green-thumb-6a158',
    storageBucket: 'green-thumb-6a158.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv6NV2h6kHTg_77NRbUqcP8X9L9geiT7E',
    appId: '1:198070192196:ios:411d7883f7c3f0fd1c5411',
    messagingSenderId: '198070192196',
    projectId: 'green-thumb-6a158',
    storageBucket: 'green-thumb-6a158.appspot.com',
    iosBundleId: 'com.example.green',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv6NV2h6kHTg_77NRbUqcP8X9L9geiT7E',
    appId: '1:198070192196:ios:411d7883f7c3f0fd1c5411',
    messagingSenderId: '198070192196',
    projectId: 'green-thumb-6a158',
    storageBucket: 'green-thumb-6a158.appspot.com',
    iosBundleId: 'com.example.green',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGRtRDux0la6fsSv9eGWVNSPP2Efn3CV0',
    appId: '1:198070192196:web:2dfb933e7584e7451c5411',
    messagingSenderId: '198070192196',
    projectId: 'green-thumb-6a158',
    authDomain: 'green-thumb-6a158.firebaseapp.com',
    storageBucket: 'green-thumb-6a158.appspot.com',
  );
}
